# Generated by Django 4.2.4 on 2025-12-14 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TrainTicketBooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
